sudo: false

language: node_js

os:
  - windows
  - linux

node_js:
  - 8
  - 10
  - 11

notifications:
  email: false

branches:
  only:
    - master
    - v3

cache:
  directories:
    - "$HOME/.npm"
